[project]
name = "simprag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "mcp",
  "sentence-transformers",
  "pymilvus[milvus-lite]",
  "docling",
  "setuptools>=82.0.0",
  "wheel>=0.46.3",
]
