[project]
name = "simprag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "mcp",
  "sentence-transformers",
  "pymilvus",
  "docling",
  # "mcp-server-fastmcp",
  # torch 
]
